references = {
    "Ha Noi": "1",
    "Ho Chi Minh City": "2",
    "Da Nang": "3",
    "Hai Phong": "4",
    "Bien Hoa": "5",
    "Hue": "6",
    "Nha Trang": "7",
    "Can Tho": "8",
    "Rach Gia": "9",
    "Quy Nhon": "10",
    "Vung Tau": "11",
    "Nam Dinh": "12",
    "Phan Thiet": "13",
    "Long Xuyen": "14",
    "Ha Long": "15",
    "Buon Ma Thuot": "16",
    "Cam Ranh": "17",
    "Cam Pha Mines": "18",
    "Thai Nguyen": "19",
    "Da Lat": "20",
    "My Tho": "21",
    "Soc Trang": "22",
    "Pleiku": "23",
    "Thanh Hoa": "24",
    "Ca Mau": "25",
    "Bac Lieu": "26",
    "Yen Vinh": "27",
    "Hoa Binh": "28",
    "Vinh Long": "29",
    "Yen Bai": "30",
    "Viet Tri": "31",
    "Phan Rang-Thap Cham": "32",
    "Chau Doc": "33",
    "Tuy Hoa": "34",
    "Tan An": "35",
    "Uong Bi": "36",
    "Sa Dec": "37",
    "Ben Tre": "38",
    "Tam Ky": "39",
    "Hai Duong": "40",
    "Tra Vinh": "41",
    "Bim Son": "42",
    "Bac Giang": "43",
    "Thai Binh": "44",
    "Ha Dong": "45",
    "Phu Khuong": "46",
    "Kon Tum": "47",
    "Bac Ninh": "48",
    "Cao Bang": "49",
    "Son Tay": "50",
    "Cu Chi": "51",
    "Tay Ninh": "52",
    "Moc Bai": "53",
    "Mui Ne": "54",
    "Dalat": "55",
    "Phuoc Son": "56",
    "Hoi An": "57",
    "Qui Nhon": "58",
    "Dong Hoi": "59",
    "Vinh": "60",
    "Ninh Binh": "61",
    "Mai Chau": "62",
    "Ha Long City": "63",
    "Mai Chau": "64",
    "Son La": "65",
    "Dien Bien Phu": "66",
    "Muong Lay": "67",
    "Sapa": "68",
    "Lao Cai": "69",
    "Bac Ha": "70"
}